# Exercise Pattern Prediction

In [2]:
# Importing dataset via kaggle

!kaggle datasets download -d athniv/exercisepatternpredict

Dataset URL: https://www.kaggle.com/datasets/athniv/exercisepatternpredict
License(s): unknown
 83%|███████████████████████████████▋      | 2.00M/2.40M [00:01<00:00, 1.33MB/s]
100%|██████████████████████████████████████| 2.40M/2.40M [00:01<00:00, 1.34MB/s]


In [3]:
# Exporting dataset from zipfile

import zipfile
zip_ref = zipfile.ZipFile('/home/bhxveshhh/ML/Exercise Pattern Prediction/exercisepatternpredict.zip', 'r')
zip_ref.extractall('/home/bhxveshhh/ML/Exercise Pattern Prediction')
zip_ref.close()

## Explaratory Data Analysis

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [5]:
df = pd.read_csv('pml-training.csv')

In [6]:
df.head()

Unnamed: 0 user_name  raw_timestamp_part_1  raw_timestamp_part_2  \
0           1  carlitos            1323084231                788290   
1           2  carlitos            1323084231                808298   
2           3  carlitos            1323084231                820366   
3           4  carlitos            1323084232                120339   
4           5  carlitos            1323084232                196328   

     cvtd_timestamp new_window  num_window  roll_belt  pitch_belt  yaw_belt  \
0  05/12/2011 11:23         no          11       1.41        8.07     -94.4   
1  05/12/2011 11:23         no          11       1.41        8.07     -94.4   
2  05/12/2011 11:23         no          11       1.42        8.07     -94.4   
3  05/12/2011 11:23         no          12       1.48        8.05     -94.4   
4  05/12/2011 11:23         no          12       1.48        8.07     -94.4   

   ...  gyros_forearm_x gyros_forearm_y gyros_forearm_z accel_forearm_x  \
0  ...             0.03            0.00           -0.02             192   
1  ...             0.02            0.00           -0.02             192   
2  ...             0.03           -0.02            0.00             196   
3  ...             0.02           -0.02            0.00             189   
4  ...             0.02            0.00           -0.02             189   

  accel_forearm_y accel_forearm_z magnet_forearm_x  magnet_forearm_y  \
0             203            -215              -17             654.0   
1             203            -216              -18             661.0   
2             204            -213              -18             658.0   
3             206            -214              -16             658.0   
4             206            -214              -17             655.0   

   magnet_forearm_z classe  
0             476.0      A  
1             473.0      A  
2             469.0      A  
3             469.0      A  
4             473.0      A  

[5 rows x 160 columns]

In [7]:
df.shape

(19622, 160)

In [8]:
df.size

3139520

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19622 entries, 0 to 19621
Columns: 160 entries, Unnamed: 0 to classe
dtypes: float64(94), int64(29), object(37)
memory usage: 24.0+ MB


In [10]:
df.describe().T

count          mean            std           min  \
Unnamed: 0            19622.0  9.811500e+03    5664.527827  1.000000e+00   
raw_timestamp_part_1  19622.0  1.322827e+09  204927.679809  1.322490e+09   
raw_timestamp_part_2  19622.0  5.006561e+05  288222.879958  2.940000e+02   
num_window            19622.0  4.306400e+02     247.909554  1.000000e+00   
roll_belt             19622.0  6.440720e+01      62.750255 -2.890000e+01   
...                       ...           ...            ...           ...   
accel_forearm_y       19622.0  1.636559e+02     200.130082 -6.320000e+02   
accel_forearm_z       19622.0 -5.529192e+01     138.396947 -4.460000e+02   
magnet_forearm_x      19622.0 -3.125759e+02     346.958482 -1.280000e+03   
magnet_forearm_y      19622.0  3.801164e+02     509.373742 -8.960000e+02   
magnet_forearm_z      19622.0  3.936137e+02     369.268747 -9.730000e+02   

                               25%           50%           75%           max  
Unnamed: 0            4.906250e+03  9.811500e+03  1.471675e+04  1.962200e+04  
raw_timestamp_part_1  1.322673e+09  1.322833e+09  1.323084e+09  1.323095e+09  
raw_timestamp_part_2  2.529122e+05  4.963800e+05  7.518908e+05  9.988010e+05  
num_window            2.220000e+02  4.240000e+02  6.440000e+02  8.640000e+02  
roll_belt             1.100000e+00  1.130000e+02  1.230000e+02  1.620000e+02  
...                            ...           ...           ...           ...  
accel_forearm_y       5.700000e+01  2.010000e+02  3.120000e+02  9.230000e+02  
accel_forearm_z      -1.820000e+02 -3.900000e+01  2.600000e+01  2.910000e+02  
magnet_forearm_x     -6.160000e+02 -3.780000e+02 -7.300000e+01  6.720000e+02  
magnet_forearm_y      2.000000e+00  5.910000e+02  7.370000e+02  1.480000e+03  
magnet_forearm_z      1.910000e+02  5.110000e+02  6.530000e+02  1.090000e+03  

[123 rows x 8 columns]

In [11]:
df.isnull().sum()

Unnamed: 0              0
user_name               0
raw_timestamp_part_1    0
raw_timestamp_part_2    0
cvtd_timestamp          0
                       ..
accel_forearm_z         0
magnet_forearm_x        0
magnet_forearm_y        0
magnet_forearm_z        0
classe                  0
Length: 160, dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.nunique()

Unnamed: 0              19622
user_name                   6
raw_timestamp_part_1      837
raw_timestamp_part_2    16783
cvtd_timestamp             20
                        ...  
accel_forearm_z           580
magnet_forearm_x         1524
magnet_forearm_y         1872
magnet_forearm_z         1683
classe                      5
Length: 160, dtype: int64

In [14]:
df['classe'].value_counts()

classe
A    5580
B    3797
E    3607
C    3422
D    3216
Name: count, dtype: int64

## Data Preprocessing

In [ ]:
# Dropping unwanted columns

df.drop(columns=['Unnamed: 0','cvtd_timestamp'], inplace=True)

In [18]:
X = df.drop(columns=['classe'])
y = df['classe']

In [19]:
# Train test split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [26]:
# Standard Scaler

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Select only numeric columns for scaling
numeric_cols = X_train.select_dtypes(include=['float64', 'int64']).columns
X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

## Model Building

In [27]:
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier, BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [28]:
logistic_clf = LogisticRegression()
ridge_clf = RidgeClassifier()
xgboost_clf = XGBClassifier()
random_forest_clf = RandomForestClassifier()
ada_boost_clf = AdaBoostClassifier()
grad_boost_clf = GradientBoostingClassifier()
bagging_clf = BaggingClassifier()
decision_tree_clf = DecisionTreeClassifier()
svm_clf = SVC()

In [31]:
# Ensure X_train and X_test contain only numeric columns and no missing values
from sklearn.preprocessing import LabelEncoder

# Encode target variable
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

X_train_clean = X_train.select_dtypes(include=['float64', 'int64']).fillna(0)
X_test_clean = X_test.select_dtypes(include=['float64', 'int64']).fillna(0)

model_li = [logistic_clf, ridge_clf, xgboost_clf, random_forest_clf, 
            ada_boost_clf, grad_boost_clf, bagging_clf, decision_tree_clf, svm_clf]

scores = []
for model in model_li:
    model.fit(X_train_clean, y_train_encoded)
    scores.append(accuracy_score(y_test_encoded, model.predict(X_test_clean)))

print(scores)

[0.8598726114649682, 0.7984713375796179, 0.9984713375796178, 0.9994904458598726, 0.6952866242038217, 0.9989808917197452, 0.9979617834394905, 0.9923566878980892, 0.954140127388535]


## Model Evalaution

In [34]:
for model in model_li:
    model.fit(X_train_clean, y_train_encoded)
    y_pred = model.predict(X_test_clean)

    print(f"Model: {model.__class__.__name__}")
    # Decode y_pred back to original string labels
    y_pred_decoded = encoder.inverse_transform(y_pred)

    print("Classification Report:\n", classification_report(y_test, y_pred_decoded))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_decoded))

    # Plot the confusion matrix
    plt.figure(figsize=(5, 4))
    sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt="d", cmap="Blues")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.title(f"Confusion Matrix - {model.__class__.__name__}")
    plt.show()

Model: LogisticRegression
Classification Report:
               precision    recall  f1-score   support

           A       0.92      0.96      0.94      1112
           B       0.82      0.78      0.80       766
           C       0.78      0.83      0.81       703
           D       0.84      0.81      0.83       653
           E       0.91      0.87      0.89       691

    accuracy                           0.86      3925
   macro avg       0.85      0.85      0.85      3925
weighted avg       0.86      0.86      0.86      3925

Confusion Matrix:
 [[1063   36    8    5    0]
 [  88  595   58    4   21]
 [   7   55  587   43   11]
 [   2   16   74  532   29]
 [   1   20   21   51  598]]


ValueError: Mix of label input types (string and number)

<Figure size 500x400 with 0 Axes>